"""todo add

Revision ID: 0bc965e81ac2
Revises: 885bd3e3e9d0
Create Date: 2024-05-26 18:24:12.284614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc965e81ac2'
down_revision = '885bd3e3e9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
